// <auto-generated />
using System;
using InsurancePropostaService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace InsurancePropostaService.Migrations
{
    [DbContext(typeof(InsuranceDbContext))]
    partial class InsuranceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("InsurancePropostaService.Models.ContratoProposta", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("dataVigenciaFim")
                        .HasColumnType("date");

                    b.Property<DateOnly>("dataVigenciaInicio")
                        .HasColumnType("date");

                    b.Property<string>("idProposta")
                        .HasColumnType("text");

                    b.HasKey("id");

                    b.HasIndex("idProposta");

                    b.ToTable("ContratoProposta");
                });

            modelBuilder.Entity("InsurancePropostaService.Models.Proposta", b =>
                {
                    b.Property<string>("id")
                        .HasColumnType("text");

                    b.Property<string>("automovel")
                        .HasColumnType("text");

                    b.Property<string>("condutor")
                        .HasColumnType("text");

                    b.Property<DateTime>("dataAtualizacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("fatorPeso")
                        .HasColumnType("numeric");

                    b.Property<int>("statusProposta")
                        .HasColumnType("integer");

                    b.Property<decimal>("valorAutomovel")
                        .HasColumnType("numeric");

                    b.Property<decimal>("valorProposta")
                        .HasColumnType("numeric");

                    b.HasKey("id");

                    b.ToTable("Proposta");
                });

            modelBuilder.Entity("InsurancePropostaService.Models.ContratoProposta", b =>
                {
                    b.HasOne("InsurancePropostaService.Models.Proposta", "proposta")
                        .WithMany()
                        .HasForeignKey("idProposta");

                    b.Navigation("proposta");
                });
#pragma warning restore 612, 618
        }
    }
}
